### ISSUE TITLE
Add ability to pass tags or extras to the scope

### ISSUE THREAD

**Issue by MRigal** [untitaker/pytest-sentry#3]
Hi @untitaker !

First of all thanks for this great Pytest plugin!
I would be interested in a way to be able to add tags or extras, as defined here: https://docs.sentry.io/enriching-error-data/additional-data/?platform=python

In my case, I would love to be able to pass the failing Job URL as extras to be able to open it.

How do you think this could be achieved?

Best,
Matthieu

**Comment by untitaker** [comment]
Hi @MRigal, hope this helps (in either conftest.py or random test file):

```
hub = Hub(Client("DSN"))
with hub:
    sentry_sdk.set_tag("...", "...")

pytestmarker = pytest.mark.sentry_client(hub)
```
